export interface EmojiEntry {
  e: string;
  n: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { e: '😀', n: 'grinning face' },
      { e: '😃', n: 'grinning face big eyes' },
      { e: '😄', n: 'grinning face smiling eyes' },
      { e: '😁', n: 'beaming face' },
      { e: '😆', n: 'grinning squinting face' },
      { e: '😅', n: 'grinning face sweat' },
      { e: '🤣', n: 'rolling on floor laughing' },
      { e: '😂', n: 'face tears of joy' },
      { e: '🙂', n: 'slightly smiling face' },
      { e: '🙃', n: 'upside down face' },
      { e: '😉', n: 'winking face' },
      { e: '😊', n: 'smiling face blushing' },
      { e: '😇', n: 'smiling face halo' },
      { e: '🥰', n: 'smiling face hearts' },
      { e: '😍', n: 'smiling face heart eyes' },
      { e: '🤩', n: 'star struck' },
      { e: '😘', n: 'face blowing kiss' },
      { e: '😗', n: 'kissing face' },
      { e: '😚', n: 'kissing face closed eyes' },
      { e: '😙', n: 'kissing face smiling eyes' },
      { e: '🥲', n: 'smiling face tear' },
      { e: '😋', n: 'face savoring food' },
      { e: '😛', n: 'face tongue' },
      { e: '😜', n: 'winking face tongue' },
      { e: '🤪', n: 'zany face' },
      { e: '😝', n: 'squinting face tongue' },
      { e: '🤑', n: 'money mouth face' },
      { e: '🤗', n: 'hugging face' },
      { e: '🤭', n: 'face hand over mouth' },
      { e: '🤫', n: 'shushing face' },
      { e: '🤔', n: 'thinking face' },
      { e: '🤐', n: 'zipper mouth face' },
      { e: '🤨', n: 'face raised eyebrow' },
      { e: '😐', n: 'neutral face' },
      { e: '😑', n: 'expressionless face' },
      { e: '😶', n: 'face without mouth' },
      { e: '😏', n: 'smirking face' },
      { e: '😒', n: 'unamused face' },
      { e: '🙄', n: 'face rolling eyes' },
      { e: '😬', n: 'grimacing face' },
      { e: '🤥', n: 'lying face' },
      { e: '😌', n: 'relieved face' },
      { e: '😔', n: 'pensive face' },
      { e: '😪', n: 'sleepy face' },
      { e: '🤤', n: 'drooling face' },
      { e: '😴', n: 'sleeping face' },
      { e: '😷', n: 'face medical mask' },
      { e: '🤒', n: 'face thermometer' },
      { e: '🤕', n: 'face head bandage' },
      { e: '🤢', n: 'nauseated face' },
      { e: '🤮', n: 'face vomiting' },
      { e: '🤧', n: 'sneezing face' },
      { e: '🥵', n: 'hot face' },
      { e: '🥶', n: 'cold face' },
      { e: '🥴', n: 'woozy face' },
      { e: '😵', n: 'dizzy face' },
      { e: '🤯', n: 'exploding head' },
      { e: '🤠', n: 'cowboy hat face' },
      { e: '🥳', n: 'partying face' },
      { e: '🥸', n: 'disguised face' },
      { e: '😎', n: 'smiling face sunglasses' },
      { e: '🤓', n: 'nerd face' },
      { e: '🧐', n: 'face monocle' },
      { e: '😕', n: 'confused face' },
      { e: '😟', n: 'worried face' },
      { e: '🙁', n: 'slightly frowning face' },
      { e: '☹️', n: 'frowning face' },
      { e: '😮', n: 'face open mouth' },
      { e: '😯', n: 'hushed face' },
      { e: '😲', n: 'astonished face' },
      { e: '😳', n: 'flushed face' },
      { e: '🥺', n: 'pleading face' },
      { e: '😦', n: 'frowning face open mouth' },
      { e: '😧', n: 'anguished face' },
      { e: '😨', n: 'fearful face' },
      { e: '😰', n: 'anxious face sweat' },
      { e: '😥', n: 'sad but relieved face' },
      { e: '😢', n: 'crying face' },
      { e: '😭', n: 'loudly crying face' },
      { e: '😱', n: 'face screaming in fear' },
      { e: '😖', n: 'confounded face' },
      { e: '😣', n: 'persevering face' },
      { e: '😞', n: 'disappointed face' },
      { e: '😓', n: 'downcast face sweat' },
      { e: '😩', n: 'weary face' },
      { e: '😫', n: 'tired face' },
      { e: '🥱', n: 'yawning face' },
      { e: '😤', n: 'triumph face' },
      { e: '😡', n: 'pouting face' },
      { e: '😠', n: 'angry face' },
      { e: '🤬', n: 'face symbols mouth' },
      { e: '😈', n: 'smiling face horns' },
      { e: '👿', n: 'angry face horns' },
      { e: '💀', n: 'skull' },
      { e: '💩', n: 'pile of poo' },
      { e: '🤡', n: 'clown face' },
      { e: '👻', n: 'ghost' },
      { e: '👽', n: 'alien' },
      { e: '🤖', n: 'robot' },
      { e: '😺', n: 'grinning cat' },
      { e: '😸', n: 'grinning cat smiling eyes' },
      { e: '😹', n: 'cat joy' },
      { e: '😻', n: 'smiling cat heart eyes' },
      { e: '😼', n: 'cat wry smile' },
      { e: '😽', n: 'kissing cat' },
      { e: '🙀', n: 'weary cat' },
      { e: '😿', n: 'crying cat' },
      { e: '😾', n: 'pouting cat' },
    ],
  },
  {
    id: 'people',
    label: 'People & Body',
    icon: '👋',
    emojis: [
      { e: '👋', n: 'waving hand' },
      { e: '🤚', n: 'raised back of hand' },
      { e: '🖐️', n: 'hand fingers splayed' },
      { e: '✋', n: 'raised hand' },
      { e: '🖖', n: 'vulcan salute' },
      { e: '👌', n: 'ok hand' },
      { e: '🤌', n: 'pinched fingers' },
      { e: '✌️', n: 'victory hand' },
      { e: '🤞', n: 'crossed fingers' },
      { e: '🤟', n: 'love you gesture' },
      { e: '🤘', n: 'sign of the horns' },
      { e: '🤙', n: 'call me hand' },
      { e: '👈', n: 'backhand index left' },
      { e: '👉', n: 'backhand index right' },
      { e: '👆', n: 'backhand index up' },
      { e: '🖕', n: 'middle finger' },
      { e: '👇', n: 'backhand index down' },
      { e: '☝️', n: 'index pointing up' },
      { e: '👍', n: 'thumbs up' },
      { e: '👎', n: 'thumbs down' },
      { e: '✊', n: 'raised fist' },
      { e: '👊', n: 'oncoming fist' },
      { e: '🤛', n: 'left facing fist' },
      { e: '🤜', n: 'right facing fist' },
      { e: '👏', n: 'clapping hands' },
      { e: '🙌', n: 'raising hands' },
      { e: '👐', n: 'open hands' },
      { e: '🤲', n: 'palms up together' },
      { e: '🤝', n: 'handshake' },
      { e: '🙏', n: 'folded hands' },
      { e: '✍️', n: 'writing hand' },
      { e: '💅', n: 'nail polish' },
      { e: '🤳', n: 'selfie' },
      { e: '💪', n: 'flexed biceps' },
      { e: '🦵', n: 'leg' },
      { e: '🦶', n: 'foot' },
      { e: '👂', n: 'ear' },
      { e: '🦻', n: 'ear hearing aid' },
      { e: '👃', n: 'nose' },
      { e: '🧠', n: 'brain' },
      { e: '👀', n: 'eyes' },
      { e: '👁️', n: 'eye' },
      { e: '👅', n: 'tongue' },
      { e: '👄', n: 'mouth' },
    ],
  },
  {
    id: 'nature',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { e: '🐶', n: 'dog face' },
      { e: '🐱', n: 'cat face' },
      { e: '🐭', n: 'mouse face' },
      { e: '🐹', n: 'hamster' },
      { e: '🐰', n: 'rabbit face' },
      { e: '🦊', n: 'fox' },
      { e: '🐻', n: 'bear' },
      { e: '🐼', n: 'panda' },
      { e: '🐨', n: 'koala' },
      { e: '🐯', n: 'tiger face' },
      { e: '🦁', n: 'lion' },
      { e: '🐮', n: 'cow face' },
      { e: '🐷', n: 'pig face' },
      { e: '🐸', n: 'frog' },
      { e: '🐵', n: 'monkey face' },
      { e: '🦆', n: 'duck' },
      { e: '🦅', n: 'eagle' },
      { e: '🦉', n: 'owl' },
      { e: '🦋', n: 'butterfly' },
      { e: '🐝', n: 'honeybee' },
      { e: '🌸', n: 'cherry blossom' },
      { e: '🌺', n: 'hibiscus' },
      { e: '🌻', n: 'sunflower' },
      { e: '🌹', n: 'rose' },
      { e: '🍀', n: 'four leaf clover' },
      { e: '🌿', n: 'herb' },
      { e: '🌱', n: 'seedling' },
      { e: '🌳', n: 'deciduous tree' },
      { e: '🌊', n: 'water wave' },
      { e: '🔥', n: 'fire' },
      { e: '⭐', n: 'star' },
      { e: '🌈', n: 'rainbow' },
      { e: '☀️', n: 'sun' },
      { e: '🌙', n: 'crescent moon' },
      { e: '⛄', n: 'snowman' },
      { e: '🌍', n: 'globe europe africa' },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { e: '🍕', n: 'pizza' },
      { e: '🍔', n: 'hamburger' },
      { e: '🍟', n: 'french fries' },
      { e: '🌮', n: 'taco' },
      { e: '🌯', n: 'burrito' },
      { e: '🍿', n: 'popcorn' },
      { e: '🍩', n: 'doughnut' },
      { e: '🍪', n: 'cookie' },
      { e: '🎂', n: 'birthday cake' },
      { e: '🍰', n: 'shortcake' },
      { e: '🧁', n: 'cupcake' },
      { e: '🍦', n: 'soft ice cream' },
      { e: '🍫', n: 'chocolate bar' },
      { e: '🍬', n: 'candy' },
      { e: '🍭', n: 'lollipop' },
      { e: '☕', n: 'hot beverage' },
      { e: '🧋', n: 'bubble tea' },
      { e: '🍺', n: 'beer mug' },
      { e: '🥂', n: 'clinking glasses' },
      { e: '🍷', n: 'wine glass' },
      { e: '🍎', n: 'red apple' },
      { e: '🍊', n: 'tangerine' },
      { e: '🍋', n: 'lemon' },
      { e: '🍇', n: 'grapes' },
      { e: '🍓', n: 'strawberry' },
      { e: '🍒', n: 'cherries' },
      { e: '🥑', n: 'avocado' },
      { e: '🥦', n: 'broccoli' },
    ],
  },
  {
    id: 'activity',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { e: '⚽', n: 'soccer ball' },
      { e: '🏀', n: 'basketball' },
      { e: '🏈', n: 'american football' },
      { e: '⚾', n: 'baseball' },
      { e: '🎾', n: 'tennis' },
      { e: '🏐', n: 'volleyball' },
      { e: '🏉', n: 'rugby football' },
      { e: '🎱', n: 'pool 8 ball' },
      { e: '🏓', n: 'ping pong' },
      { e: '🏸', n: 'badminton' },
      { e: '🥊', n: 'boxing glove' },
      { e: '🥋', n: 'martial arts uniform' },
      { e: '🎯', n: 'bullseye' },
      { e: '⛳', n: 'golf' },
      { e: '🎮', n: 'video game' },
      { e: '🕹️', n: 'joystick' },
      { e: '🎲', n: 'game die' },
      { e: '♟️', n: 'chess pawn' },
      { e: '🎭', n: 'performing arts' },
      { e: '🎨', n: 'artist palette' },
      { e: '🎬', n: 'clapper board' },
      { e: '🎤', n: 'microphone' },
      { e: '🎧', n: 'headphone' },
      { e: '🎵', n: 'musical note' },
      { e: '🎶', n: 'musical notes' },
      { e: '🎷', n: 'saxophone' },
      { e: '🎸', n: 'guitar' },
      { e: '🎹', n: 'musical keyboard' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { e: '✈️', n: 'airplane' },
      { e: '🚀', n: 'rocket' },
      { e: '🛸', n: 'flying saucer' },
      { e: '🚂', n: 'locomotive' },
      { e: '🚗', n: 'automobile' },
      { e: '🚕', n: 'taxi' },
      { e: '🚌', n: 'bus' },
      { e: '🚔', n: 'police car' },
      { e: '🚑', n: 'ambulance' },
      { e: '🚒', n: 'fire engine' },
      { e: '🏠', n: 'house' },
      { e: '🏢', n: 'office building' },
      { e: '🏰', n: 'castle' },
      { e: '🗼', n: 'tokyo tower' },
      { e: '🗽', n: 'statue of liberty' },
      { e: '⛪', n: 'church' },
      { e: '🌁', n: 'foggy' },
      { e: '🌃', n: 'night with stars' },
      { e: '🌉', n: 'bridge at night' },
      { e: '🗺️', n: 'world map' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { e: '💡', n: 'light bulb' },
      { e: '🔦', n: 'flashlight' },
      { e: '📱', n: 'mobile phone' },
      { e: '💻', n: 'laptop' },
      { e: '⌨️', n: 'keyboard' },
      { e: '🖥️', n: 'desktop computer' },
      { e: '🖨️', n: 'printer' },
      { e: '📷', n: 'camera' },
      { e: '📸', n: 'camera with flash' },
      { e: '📹', n: 'video camera' },
      { e: '📺', n: 'television' },
      { e: '📻', n: 'radio' },
      { e: '📞', n: 'telephone receiver' },
      { e: '📡', n: 'satellite antenna' },
      { e: '🔋', n: 'battery' },
      { e: '🔌', n: 'electric plug' },
      { e: '💾', n: 'floppy disk' },
      { e: '💿', n: 'optical disk' },
      { e: '📀', n: 'dvd' },
      { e: '🧲', n: 'magnet' },
      { e: '🔧', n: 'wrench' },
      { e: '🔨', n: 'hammer' },
      { e: '⚙️', n: 'gear' },
      { e: '🔩', n: 'nut and bolt' },
      { e: '🔑', n: 'key' },
      { e: '🗝️', n: 'old key' },
      { e: '💊', n: 'pill' },
      { e: '💉', n: 'syringe' },
      { e: '🩺', n: 'stethoscope' },
      { e: '🩹', n: 'adhesive bandage' },
      { e: '📚', n: 'books' },
      { e: '📖', n: 'open book' },
      { e: '✏️', n: 'pencil' },
      { e: '🖊️', n: 'pen' },
      { e: '📌', n: 'pushpin' },
      { e: '📎', n: 'paperclip' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      { e: '❤️', n: 'red heart' },
      { e: '🧡', n: 'orange heart' },
      { e: '💛', n: 'yellow heart' },
      { e: '💚', n: 'green heart' },
      { e: '💙', n: 'blue heart' },
      { e: '💜', n: 'purple heart' },
      { e: '🖤', n: 'black heart' },
      { e: '🤍', n: 'white heart' },
      { e: '🤎', n: 'brown heart' },
      { e: '💔', n: 'broken heart' },
      { e: '❣️', n: 'heart exclamation' },
      { e: '💕', n: 'two hearts' },
      { e: '💞', n: 'revolving hearts' },
      { e: '💓', n: 'beating heart' },
      { e: '💗', n: 'growing heart' },
      { e: '💖', n: 'sparkling heart' },
      { e: '💘', n: 'heart with arrow' },
      { e: '💝', n: 'heart with ribbon' },
      { e: '💟', n: 'heart decoration' },
      { e: '☮️', n: 'peace symbol' },
      { e: '✝️', n: 'cross' },
      { e: '☯️', n: 'yin yang' },
      { e: '✅', n: 'check mark button' },
      { e: '❌', n: 'cross mark' },
      { e: '⭕', n: 'hollow red circle' },
      { e: '🔴', n: 'red circle' },
      { e: '🟠', n: 'orange circle' },
      { e: '🟡', n: 'yellow circle' },
      { e: '🟢', n: 'green circle' },
      { e: '🔵', n: 'blue circle' },
      { e: '🟣', n: 'purple circle' },
      { e: '⚫', n: 'black circle' },
      { e: '⚪', n: 'white circle' },
      { e: '🔶', n: 'large orange diamond' },
      { e: '🔷', n: 'large blue diamond' },
      { e: '⚡', n: 'high voltage' },
      { e: '🌟', n: 'glowing star' },
      { e: '💫', n: 'dizzy' },
      { e: '✨', n: 'sparkles' },
      { e: '🎉', n: 'party popper' },
      { e: '🎊', n: 'confetti ball' },
      { e: '🎈', n: 'balloon' },
      { e: '🎁', n: 'wrapped gift' },
      { e: '🏆', n: 'trophy' },
      { e: '🥇', n: 'first place medal' },
      { e: '🎖️', n: 'military medal' },
    ],
  },
];
