spring.application.name=app
spring.datasource.url=jdbc:mysql://localhost:3306/chatdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dk@reddy001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update      
spring.mail.host=smtp.gmail.com              
spring.mail.port=587      
spring.jpa.open-in-view=false                  
email.username=dkreddy005@gmail.com
email.password=vizb rbyp epkk souw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=chatapplication12;AccountKey=V1pf7LRM2gPHcjZ4SG7jGlTVdk1jrC80ZpdPykiLJ3wSjK+Do/kMrq4g1Zxkh0kFBD4K64Usil1O+AStRJKegg==;EndpointSuffix=core.windows.net
azure.storage.container-name=profile-images
# File upload settings
app.upload.dir=./uploads
app.upload.url-prefix=/uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
